name: CI - Kustomize Validation

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      - name: Validar Kustomize build (dev)
        run: |
          cd overlays/dev
          kustomize build .
